### ISSUE TITLE
App can create a sleep record from clock-in request

### ISSUE THREAD

**Issue by gsmendoza** [gsmendoza/sleep_record_api#1]
## Summary

Given an existing user with ID 1
When the app receives the following request: `POST /sleep_records` with the following params:
  `[sleep_record][user_id]=1`
Then the app should create a new sleep record for user 1
And the sleep record's clock-in time should be set to the current time
And the app should return a response of the new sleep record for the user

## Validations

* [x] The user should exist.
* [x] The user should have no ongoing sleep record IF the sleep record being created is also ongoing.

## TODOs

* [x] Add a translation for `has_ongoing_sleep_record`.
