### ISSUE TITLE
App can update a sleep record from clock-out request

### ISSUE THREAD

**Issue by gsmendoza** [gsmendoza/sleep_record_api#2]
## Summary 

Given an existing sleep record with ID 2
When the app receives the following request: `PATCH /sleep_records/2/clock_out`
Then the app should set the clock-out time of the sleep record to the current time
And the app should return a response of the sleep record

## Validations

* [x] The sleep record should exist.
* [x] The sleep record hasn't been clocked out.

## TODOS

* [x] Extract `SleepRecord.new_clock_in(sleep_record_params)`
* [x] Fix "has ongoing sleep record".
